<?php
/*
**
**
** Simple tool for anonymizing posts from the front end
** Maybe add anonymize users
** Step 1 - check if current user is admin
** Step 2 - Load anonymization data               //obtain current post author id
** Step 3 - update the post with said data, maybe save a record of original author
**
**
**
*/
//Don't show this if the post is already from qtxanon....
function qtxAnon_initialize() {
  if (qtx_is_staff() && function_exists('qtxAnon_exec')) {
    $user_name = "QTXAnnonBOT";
    $user_id = username_exists( $user_name );
    if ( ! $user_id ) {
      echo "<br>The user id " . $user_id;
      echo "<br>The user name " . $user_name;
      echo "We are inside the user creation";
      $random_password = wp_generate_password( $length = 20, $include_standard_special_chars = false );
      $user_id = wp_create_user( $user_name, $random_password );
      echo "<br>The user id " . $user_id;
      echo "<br>The user name " . $user_name;
      echo "<br>The user password " . $random_password;
      $post_content = "<br>The user id " . $user_id . "<br>The user name " . $user_name . "<br>The user password " . $random_password . "<br>lenght " . $length;
      $my_post = array(
        'post_title'    => "QTXAnnonBOT user data generated by qtxAnon",
        'post_content'  => $post_content,
        'post_status'   => 'draft',
        'post_author'   => 1,
      );
      wp_insert_post( $my_post );
    }
    qtxAnon_exec($user_id);
  }
}
//Is the current user part of quartex staff
if (qtx_is_staff()) {
  //call this function to initialize, pass it the user id of the "anon user"
  function qtxAnon_exec($user_id) {
    //Are we in the loop?
    if ( is_singular( 'post' ) && in_the_loop() ) {
      //Echoes the form (a submit button with a hidden input)
      qtxAnon_echoButton();
      //Is the hidden input set?
      if(isset($_POST['qtxAnon'])) {
        $args = array(
          'ID' => get_the_ID(),
          'post_author' => $user_id,
        );
        wp_update_post($args);
      }
    }
  }
  function qtxAnon_echoButton() { ?>
    <form method="post">
      <input type="hidden" id="qtxAnon" name="qtxAnon" value="yes">
     <input type="submit" value="Annonymize">
    </form>
<?php
  }
}
 ?>
